name: Build Flutter APKs & Appbundle
on: [workflow_dispatch]

jobs:
  # Build APKs
  build_apks:
    name: Build DEV APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Initialize project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'     

      - name: Build APKs (Split by ABI)
        run: flutter build apk --release --split-per-abi
 
      - name: Release the APKs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.project_version.outputs.version_number }}
          name: "Built Apks ${{ steps.project_version.outputs.version_number }}"
          body: "Built apks of this project, can be use to test the application"

  # Build Appbundle
  build_appbundle:
    name: Build APPBUNDLE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Get project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'    

      - name: Build Appbundle
        run: flutter build appbundle

      - name: Release Appbundle
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/*.aab"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.project_version.outputs.version_number }}-appbundle
          name: "Built Appbundle ${{ steps.project_version.outputs.version_number }}"
          body: "Built Appbundle, can be use to upload the application to playstore"